package domainModel;
// Generated 14-ene-2012 13:11:09 by Hibernate Tools 3.2.1.GA

/**
 * BonsHotels generated by hbm2java
 */
public class BonsHotels  implements java.io.Serializable {

    private BonsHotelsId id;

    public BonsHotels() {
    }

    public BonsHotels(BonsHotelsId id) {
       this.id = id;
    }
   
    public BonsHotelsId getId() {
        return this.id;
    }
    
    public void setId(BonsHotelsId id) {
        this.id = id;
    }




}


