package domainModel;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ComentariId generated by hbm2java
 */
public class ComentariId  implements java.io.Serializable {


     private String nomHotel;
     private String dniClient;
     private Date dataComentari;

    public ComentariId() {
    }

    public ComentariId(String nomHotel, String dniClient, Date dataComentari) {
       this.nomHotel = nomHotel;
       this.dniClient = dniClient;
       this.dataComentari = dataComentari;
    }
   
    public String getNomHotel() {
        return this.nomHotel;
    }
    
    public void setNomHotel(String nomHotel) {
        this.nomHotel = nomHotel;
    }
    public String getDniClient() {
        return this.dniClient;
    }
    
    public void setDniClient(String dniClient) {
        this.dniClient = dniClient;
    }
    public Date getDataComentari() {
        return this.dataComentari;
    }
    
    public void setDataComentari(Date dataComentari) {
        this.dataComentari = dataComentari;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComentariId) ) return false;
		 ComentariId castOther = ( ComentariId ) other; 
         
		 return ( (this.getNomHotel()==castOther.getNomHotel()) || ( this.getNomHotel()!=null && castOther.getNomHotel()!=null && this.getNomHotel().equals(castOther.getNomHotel()) ) )
 && ( (this.getDniClient()==castOther.getDniClient()) || ( this.getDniClient()!=null && castOther.getDniClient()!=null && this.getDniClient().equals(castOther.getDniClient()) ) )
 && ( (this.getDataComentari()==castOther.getDataComentari()) || ( this.getDataComentari()!=null && castOther.getDataComentari()!=null && this.getDataComentari().equals(castOther.getDataComentari()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNomHotel() == null ? 0 : this.getNomHotel().hashCode() );
         result = 37 * result + ( getDniClient() == null ? 0 : this.getDniClient().hashCode() );
         result = 37 * result + ( getDataComentari() == null ? 0 : this.getDataComentari().hashCode() );
         return result;
   }   


}


