package Strategies;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA

import domainModel.PreuTipusHabitacio;




/**
 * PreuAmbPercentatge generated by hbm2java
 */
public class PreuAmbPercentatge  implements java.io.Serializable, IPreuStrategy {


    private PreuAmbPercentatgeId id;
    private Double percentatge;

    public PreuAmbPercentatge() {
    }

	
    public PreuAmbPercentatge(PreuAmbPercentatgeId id) {
        this.id = id;
    }
    public PreuAmbPercentatge(PreuAmbPercentatgeId id, Double percentatge) {
       this.id = id;
       this.percentatge = percentatge;
    }
   
    public PreuAmbPercentatgeId getId() {
        return this.id;
    }
    
    public void setId(PreuAmbPercentatgeId id) {
        this.id = id;
    }
    public Double getPercentatge() {
        return this.percentatge;
    }
    
    public void setPercentatge(Double percentatge) {
        this.percentatge = percentatge;
    }

    @Override
    public float getPreu(PreuTipusHabitacio preuTipus) {

        return (float) (preuTipus.getPreu()*(1-percentatge));
    }




}


