package Strategies;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA

import domainModel.PreuTipusHabitacio;





/**
 * PreuAmbDescompte generated by hbm2java
 */
public class PreuAmbDescompte  implements java.io.Serializable, IPreuStrategy {


    private PreuAmbDescompteId id;
    private Double descompte;

    public PreuAmbDescompte() {
    }

	
    public PreuAmbDescompte(PreuAmbDescompteId id) {
        this.id = id;
    }
    public PreuAmbDescompte(PreuAmbDescompteId id, Double descompte) {
       this.id = id;
       this.descompte = descompte;
    }
   
    public PreuAmbDescompteId getId() {
        return this.id;
    }
    
    public void setId(PreuAmbDescompteId id) {
        this.id = id;
    }
    public Double getDescompte() {
        return this.descompte;
    }
    
    public void setDescompte(Double descompte) {
        this.descompte = descompte;
    }

    @Override
    public float getPreu(PreuTipusHabitacio preuTipus) {
        
        return (float) (preuTipus.getPreu()-descompte);
    }




}


