package Strategies;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA

import domainModel.PreuTipusHabitacio;
import domainModel.PreuTipusHabitacioId;




/**
 * PreuAmbPercentatge generated by hbm2java
 */
public class PreuAmbPercentatge  implements java.io.Serializable, IPreuStrategy {


    private PreuTipusHabitacioId id;
    private Float percentatge;

    public PreuAmbPercentatge() {
    }

	
    public PreuAmbPercentatge(PreuTipusHabitacioId id) {
        this.id = id;
    }
    public PreuAmbPercentatge(PreuTipusHabitacioId id, Float percentatge) {
       this.id = id;
       this.percentatge = percentatge;
    }

    public Float getPercentatge() {
        return this.percentatge;
    }
    
    public void setPercentatge(Float percentatge) {
        this.percentatge = percentatge;
    }

    @Override
    public float getPreu(PreuTipusHabitacio preuTipus) {

        return (preuTipus.getPreu()*(1-percentatge));
    }

    @Override
    public PreuTipusHabitacioId getId() {

        return this.id;
    }

    @Override
    public void setId(PreuTipusHabitacioId id) {

        this.id = id;
    }




}


