package Strategies;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA

import domainModel.PreuTipusHabitacio;
import domainModel.PreuTipusHabitacioId;





/**
 * PreuAmbDescompte generated by hbm2java
 */
public class PreuAmbDescompte  implements java.io.Serializable, IPreuStrategy {


    private PreuTipusHabitacioId id;
    private Float descompte;

    public PreuAmbDescompte() {
    }

	
    public PreuAmbDescompte(PreuTipusHabitacioId id) {
        this.id = id;
    }
    public PreuAmbDescompte(PreuTipusHabitacioId id, Float descompte) {
       this.id = id;
       this.descompte = descompte;
    }
   
    public Float getDescompte() {
        return this.descompte;
    }
    
    public void setDescompte(Float descompte) {
        this.descompte = descompte;
    }

    @Override
    public float getPreu(PreuTipusHabitacio preuTipus) {
        
        return (preuTipus.getPreu()-descompte);
    }

    @Override
    public PreuTipusHabitacioId getId() {

        return this.id;
    }

    @Override
    public void setId(PreuTipusHabitacioId id) {

        this.id = id;
    }




}


