package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String dni;
     private String nom;
     private String cognoms;
     private String email;

    public Client() {
    }

	
    public Client(String dni) {
        this.dni = dni;
    }
    public Client(String dni, String nom, String cognoms, String email) {
       this.dni = dni;
       this.nom = nom;
       this.cognoms = cognoms;
       this.email = email;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCognoms() {
        return this.cognoms;
    }
    
    public void setCognoms(String cognoms) {
        this.cognoms = cognoms;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


