package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * Habitacio generated by hbm2java
 */
public class Habitacio  implements java.io.Serializable {


     private HabitacioId id;
     private String nomtipus;

    public Habitacio() {
    }

	
    public Habitacio(HabitacioId id) {
        this.id = id;
    }
    public Habitacio(HabitacioId id, String nomtipus) {
       this.id = id;
       this.nomtipus = nomtipus;
    }
   
    public HabitacioId getId() {
        return this.id;
    }
    
    public void setId(HabitacioId id) {
        this.id = id;
    }
    public String getNomtipus() {
        return this.nomtipus;
    }
    
    public void setNomtipus(String nomtipus) {
        this.nomtipus = nomtipus;
    }




}


