package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * HabitacioId generated by hbm2java
 */
public class HabitacioId  implements java.io.Serializable {


     private String nomHotel;
     private int numero;

    public HabitacioId() {
    }

    public HabitacioId(String nomHotel, int numero) {
       this.nomHotel = nomHotel;
       this.numero = numero;
    }
   
    public String getNomHotel() {
        return this.nomHotel;
    }
    
    public void setNomHotel(String nomHotel) {
        this.nomHotel = nomHotel;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HabitacioId) ) return false;
		 HabitacioId castOther = ( HabitacioId ) other; 
         
		 return ( (this.getNomHotel()==castOther.getNomHotel()) || ( this.getNomHotel()!=null && castOther.getNomHotel()!=null && this.getNomHotel().equals(castOther.getNomHotel()) ) )
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNomHotel() == null ? 0 : this.getNomHotel().hashCode() );
         result = 37 * result + this.getNumero();
         return result;
   }   


}


