package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private String nom;
     private String descripcio;
     private String nomcategoria;
     private String nompoblacio;

    public Hotel() {
    }

	
    public Hotel(String nom) {
        this.nom = nom;
    }
    public Hotel(String nom, String descripcio, String nomcategoria, String nompoblacio) {
       this.nom = nom;
       this.descripcio = descripcio;
       this.nomcategoria = nomcategoria;
       this.nompoblacio = nompoblacio;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescripcio() {
        return this.descripcio;
    }
    
    public void setDescripcio(String descripcio) {
        this.descripcio = descripcio;
    }
    public String getNomcategoria() {
        return this.nomcategoria;
    }
    
    public void setNomcategoria(String nomcategoria) {
        this.nomcategoria = nomcategoria;
    }
    public String getNompoblacio() {
        return this.nompoblacio;
    }
    
    public void setNompoblacio(String nompoblacio) {
        this.nompoblacio = nompoblacio;
    }




}


