package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * Poblacio generated by hbm2java
 */
public class Poblacio  implements java.io.Serializable {


     private String nom;

    public Poblacio() {
    }

    public Poblacio(String nom) {
       this.nom = nom;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


