package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ReservaId generated by hbm2java
 */
public class ReservaId  implements java.io.Serializable {


     private String nomHotel;
     private int numero;
     private Date dataInici;

    public ReservaId() {
    }

    public ReservaId(String nomHotel, int numero, Date dataInici) {
       this.nomHotel = nomHotel;
       this.numero = numero;
       this.dataInici = dataInici;
    }
   
    public String getNomHotel() {
        return this.nomHotel;
    }
    
    public void setNomHotel(String nomHotel) {
        this.nomHotel = nomHotel;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getDataInici() {
        return this.dataInici;
    }
    
    public void setDataInici(Date dataInici) {
        this.dataInici = dataInici;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservaId) ) return false;
		 ReservaId castOther = ( ReservaId ) other; 
         
		 return ( (this.getNomHotel()==castOther.getNomHotel()) || ( this.getNomHotel()!=null && castOther.getNomHotel()!=null && this.getNomHotel().equals(castOther.getNomHotel()) ) )
 && (this.getNumero()==castOther.getNumero())
 && ( (this.getDataInici()==castOther.getDataInici()) || ( this.getDataInici()!=null && castOther.getDataInici()!=null && this.getDataInici().equals(castOther.getDataInici()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNomHotel() == null ? 0 : this.getNomHotel().hashCode() );
         result = 37 * result + this.getNumero();
         result = 37 * result + ( getDataInici() == null ? 0 : this.getDataInici().hashCode() );
         return result;
   }   


}


