package pojos;
// Generated 13-ene-2012 19:46:20 by Hibernate Tools 3.2.1.GA



/**
 * TipusHabitacio generated by hbm2java
 */
public class TipusHabitacio  implements java.io.Serializable {


     private String nom;
     private Integer capacitat;
     private String descripcio;

    public TipusHabitacio() {
    }

	
    public TipusHabitacio(String nom) {
        this.nom = nom;
    }
    public TipusHabitacio(String nom, Integer capacitat, String descripcio) {
       this.nom = nom;
       this.capacitat = capacitat;
       this.descripcio = descripcio;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Integer getCapacitat() {
        return this.capacitat;
    }
    
    public void setCapacitat(Integer capacitat) {
        this.capacitat = capacitat;
    }
    public String getDescripcio() {
        return this.descripcio;
    }
    
    public void setDescripcio(String descripcio) {
        this.descripcio = descripcio;
    }




}


